In [ ]:
# 21-1-08-Stu_Respiratory_Disease

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [4]:
# Read the csv file into a pandas DataFrame

Final_Dataset = pd.read_csv('./Resources/Final_Dataset.csv')
Final_Dataset.head()

,Region,Year,#_of_deaths,Lifetime risk (%),deaths per 100k live births,GDP per capita
0,North America,1997.0,470.0,0.020779,11.0,40981.44392
1,North America,1998.0,470.0,0.020667,11.0,42302.94407
2,North America,1996.0,480.0,0.021541,11.0,39697.16222
3,North America,1992.0,490.0,0.022674,11.0,36600.74711
4,North America,1999.0,490.0,0.021502,11.0,43809.16368

In [9]:
# Use Pandas get_dummies to convert categorical data

Final_Dataset = pd.get_dummies(Final_Dataset)
Final_Dataset.head(10)

,Year,#_of_deaths,Lifetime risk (%),deaths per 100k live births,GDP per capita,Region_East Asia & Pacific,Region_Europe & Central Asia,Region_Latin America & Caribbean,Region_Middle East & North Africa,Region_North America,Region_South Asia,Region_Sub-Saharan Africa
0,1997.0,470.0,0.020779,11.0,40981.44392,0,0,0,0,1,0,0
1,1998.0,470.0,0.020667,11.0,42302.94407,0,0,0,0,1,0,0
2,1996.0,480.0,0.021541,11.0,39697.16222,0,0,0,0,1,0,0
3,1992.0,490.0,0.022674,11.0,36600.74711,0,0,0,0,1,0,0
4,1999.0,490.0,0.021502,11.0,43809.16368,0,0,0,0,1,0,0
5,1990.0,500.0,0.023192,11.0,36485.72225,0,0,0,0,1,0,0
6,1991.0,500.0,0.023244,11.0,35910.26008,0,0,0,0,1,0,0
7,1993.0,500.0,0.022958,11.0,37118.81449,0,0,0,0,1,0,0
8,1994.0,500.0,0.022738,11.0,38170.45974,0,0,0,0,1,0,0
9,1995.0,500.0,0.022431,11.0,38757.04756,0,0,0,0,1,0,0

In [11]:
# Assign X (data) and y (target)

X = Final_Dataset[['#_of_deaths', 'deaths per 100k live births', 'GDP per capita', 'Region_Europe & Central Asia', 'Region_North America']]
y = Final_Dataset["Lifetime risk (%)"].values.reshape(-1, 1)
print(X.shape, y.shape)

(616, 5) (616, 1)

In [12]:
# Split the data into training and testing

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [13]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScater model and fit it to the training data

X_scaler = StandardScaler().fit(X_train)
y_scaler = StandardScaler().fit(y_train)

In [14]:
# Transform the training and testing data using the X_scaler and y_scaler models

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
y_train_scaled = y_scaler.transform(y_train)
y_test_scaled = y_scaler.transform(y_test)

In [22]:
# Create a LinearRegression model and fit it to the scaled training data

### BEGIN SOLUTION
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train_scaled, y_train_scaled)
-------------------------------------------------
# https://intellipaat.com/community/9684/valueerror-input-contains-nan-infinity-or-a-value-too-large-for-dtype-float64-while-preprocessing-data
# pd.isnull(train_data).sum() > 0

# df[df==np.inf]=np.nan
# df.fillna(df.mean(), inplace=True)

# df.replace([np.inf, -np.inf], np.nan, inplace=True)

### END SOLUTION

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
# Make predictions using the X_test_scaled data
# Plot y_test_scaled vs y_test_scaled
# Scatter plot y_test_scaled vs predictions

### BEGIN SOLUTION
predictions = model.predict(X_test_scaled)
model.fit(X_train_scaled, y_train_scaled)
plt.scatter(model.predict(X_train_scaled), model.predict(X_train_scaled) - y_train_scaled, c="blue", label="Training Data")
plt.scatter(model.predict(X_test_scaled), model.predict(X_test_scaled) - y_test_scaled, c="orange", label="Testing Data")
plt.legend()
plt.hlines(y=0, xmin=y_test_scaled.min(), xmax=y_test_scaled.max())
plt.title("Residual Plot")
plt.show()
### END SOLUTION

In [ ]:
# Used X_test_scaled, y_test_scaled, and model.predict(X_test_scaled) to calculate MSE and R2

### BEGIN SOLUTION
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test_scaled, predictions)
r2 = model.score(X_test_scaled, y_test_scaled)
### END SOLUTION

print(f"MSE: {MSE}, R2: {r2}")

In [ ]:
# LASSO model
# Note: Use an alpha of .01 when creating the model for this activity
from sklearn.linear_model import Lasso

### BEGIN SOLUTION
lasso = Lasso(alpha=.01).fit(X_train_scaled, y_train_scaled)

predictions = lasso.predict(X_test_scaled)

MSE = mean_squared_error(y_test_scaled, predictions)
r2 = lasso.score(X_test_scaled, y_test_scaled)
### END SOLUTION

print(f"MSE: {MSE}, R2: {r2}")

In [ ]:
# Ridge model
# Note: Use an alpha of .01 when creating the model for this activity
from sklearn.linear_model import Ridge

### BEGIN SOLUTION
ridge = Ridge(alpha=.01).fit(X_train_scaled, y_train_scaled)

predictions = ridge.predict(X_test_scaled)

MSE = mean_squared_error(y_test_scaled, predictions)
r2 = ridge.score(X_test_scaled, y_test_scaled)
### END SOLUTION

print(f"MSE: {MSE}, R2: {r2}")

In [ ]:
# ElasticNet model
# Note: Use an alpha of .01 when creating the model for this activity
from sklearn.linear_model import ElasticNet

### BEGIN SOLUTION
elasticnet = ElasticNet(alpha=.01).fit(X_train_scaled, y_train_scaled)

predictions = elasticnet.predict(X_test_scaled)

MSE = mean_squared_error(y_test_scaled, predictions)
r2 = elasticnet.score(X_test_scaled, y_test_scaled)
### END SOLUTION

print(f"MSE: {MSE}, R2: {r2}")